replicas: 1
namespace: mganin

app:
  name: "application"
  path: "application"
  version: "v8"

resources:
  requests:
    memory: "200M"
    cpu: "1"
  limits:
    memory: "200M"
    cpu: "1"

service:
  enabled: true
  type: ClusterIP
  ports:
  - name: http
    port: 5001
    protocol: TCP
    targetPort: 5001

env:
    DB_NAME: postgres
    DB_USER: postgres
    DB_PASSWORD: password
    DB_HOST: localhost
    DB_PORT: 1234
